macOS wxWidgets 3.1.5 universal binary
NREL/lk pull request #27
Opened 2021-12-29 12:25 UTC by sjanzou

2022-01-06 15:30 UTC, dguittet requested changes

2022-01-06 15:30 UTC, dguittet commented on CMakeLists.txt
> +        add_compile_options( -fno-common)
Can you remove commented code? Maybe replace with a sentence saying why you don't need `-arch x86_64 -arch arm64`?

2022-01-07 17:41 UTC, brtietz approved these changes
Looks good on Linux

2022-01-08 02:41 UTC, janinefreeman approved these changes
Works for me on Windows

2022-01-10 08:48 UTC, merged