Improve lookup error handling
NREL/lk pull request #36
Opened 2022-11-02 18:11 UTC by brtietz

Return values from REopt were causing SAM to crash. Check for a null pointer earlier to avoid the crash.

To reproduce:
- Check out develop on lk and wex, https://github.com/NREL/ssc/commit/d2f76f09d4e6f346fc8ceb16f8c53b30086f38c1 on ssc, and https://github.com/NREL/SAM/commit/d498705c6a2d112613211d64dd578009b743fb27 on SAM, build
- Open a behind the meter PV-Battery case and run "Get size and dispatch from REopt"
- Observe the crash
- Check out improve_lookup_error_handling on lk, rebuild
- Open a behind the meter PV-Battery case and run "Get size and dispatch from REopt"
- Observe the improved error message and lack of crash

2022-11-03 09:30 UTC, sjanzou requested changes
Remove comparing this to NULL and the results do not change using the branches in the pull request.

Also, on MacOS 12.6 with XCode 14.1, no crash occurs when running the debug build with or without the env.cpp change per attached document and latest commit.
[Lk pull issue 36 from Brian and email https.docx.zip](https://github.com/NREL/lk/files/9927061/Lk.pull.issue.36.from.Brian.and.email.https.docx.zip)

2022-11-03 09:30 UTC, sjanzou commented on src/env.cpp
> +    if (this == 0) throw error_t(lk_tr("access violation: expected hash table, but found null")); // Check nullptr before the next line throws uncatchable errors
In XCode 14.1 this causes a warning (which is causing the Github Actions to fail):
![image](https://user-images.githubusercontent.com/6498311/199682763-d18baa96-e646-46e1-8dce-33d592181c71.png)

2022-11-03 09:30 UTC, sjanzou commented on src/env.cpp
> +    if (this == 0) throw error_t(lk_tr("access violation: expected hash table, but found null")); // Check nullptr before the next line throws uncatchable errors
Suggest changing to the following that was tested on MacOS 12.6 with XCode 14.1
![image](https://user-images.githubusercontent.com/6498311/199686779-238ae989-acfe-403c-b8ef-4727773139d9.png)

2022-11-03 09:48 UTC, sjanzou commented
Note that the (!this) comparison does not generate a warning in XCode 14.1 but does generate a warning in the Github Actions Ubuntu build. So, either is fine. However, we must remove the -Werror from the CMakeList.txt that has been committed to this branch and pull request.

2022-11-03 16:02 UTC, brtietz commented
Thanks, I wasn't sure we wanted to remove -Werror. Were there further changes needed after [a960030](https://github.com/NREL/lk/pull/36/commits/a9600303dc68a32d8dfa344044493443bdeacc42)? This looks good to me.

2022-11-04 05:09 UTC, sjanzou approved these changes
looks good

2022-11-04 06:30 UTC, merged